kind: ServiceAccount
apiVersion: v1
metadata:
  name: clean-job-account
  namespace: catalog
  labels:
    clean-job: "true"
    app: catalog-catalog
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: clean-job-account
  labels:
    clean-job: "true"
    app: catalog-catalog
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:     ["get", "list", "update"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs:     ["list", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs:     ["list", "delete"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterserviceclasses"
    - "clusterserviceplans"
    - "clusterservicebrokers"
    - "serviceinstances"
    - "servicebindings"
    - "serviceclasses"
    - "serviceplans"
    - "servicebrokers"
    verbs: ["get", "list","update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: clean-job-account
  labels:
    clean-job: "true"
    app: catalog-catalog
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"
subjects:
  - kind: ServiceAccount
    name: clean-job-account
    namespace: catalog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clean-job-account

---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-catalog-pre-delete-clean-job
  namespace: catalog
  labels:
    app: catalog-catalog
    chart: "catalog-0.3.0"
    release: "catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        cleaner-job: "true"
        app: catalog-catalog-clean-job
        chart: "catalog-0.3.0"
        release: "catalog"
        heritage: "Tiller"
    spec:
      restartPolicy: Never
      serviceAccountName: clean-job-account
      imagePullSecrets: []
      containers:
        - name: service-catalog
          image: quay.io/kubernetes-service-catalog/service-catalog:v0.3.0
          imagePullPolicy: Always
          args:
          - cleaner
          - --cleaner-command
          - "remove-crd"
          - --service-catalog-namespace
          - catalog
          - --controller-manager-deployment
          - catalog-catalog-controller-manager
          - --webhook-configurations
          - catalog-catalog-webhook catalog-catalog-validating-webhook
